"use client";

import type { Locale } from "@/lib/i18n";

type LocaleCopy = Exclude<Locale, "en">;

const productCopy: Record<LocaleCopy, Record<string, string>> = {
  zh: {
    "Crystal-Face Aluminium Skirting": "晶面铝合金踢脚线",
    "Morandi Finish Aluminium Skirting": "莫兰迪饰面铝合金踢脚线",
    "Woodgrain Upturned Aluminium Skirting": "木纹上翻铝合金踢脚线",
    "Dual-Seal Aluminium Skirting": "双密封铝合金踢脚线",
    "Flat-Face Aluminium Skirting": "平面铝合金踢脚线",
    "Flat-Face Clip-On Aluminium Skirting": "平面卡扣式铝合金踢脚线",
    "Soft-Radius Aluminium Skirting": "柔弧铝合金踢脚线",
    "Minimal Woodgrain Aluminium Skirting": "极简木纹铝合金踢脚线",
    "Aluminium-Titanium Alloy Skirting": "铝钛合金踢脚线",
    "Seamless Recessed Aluminium Skirting": "无缝嵌入式铝合金踢脚线",
    "Standard Recessed Aluminium Skirting": "标准嵌入式铝合金踢脚线",
    "Flush-Mount Recessed Aluminium Skirting": "齐平嵌入式铝合金踢脚线",
    "Plaster-In Aluminium Skirting": "抹灰嵌入式铝合金踢脚线",
    "Recessed LED Aluminium Skirting": "嵌入式 LED 铝合金踢脚线",
    "TG Clip-On Solid Wood Skirting": "TG 卡扣式实木踢脚线",
    "TG Clip-On Solid Wood Skirting System": "TG 卡扣式实木踢脚线系统",
    "Three-Side Painted Solid Wood Skirting": "三面漆实木踢脚线",
    "Xuanwu & Qilin Solid Wood Series": "玄武与麒麟实木系列",
    "Classic 201 Stainless Steel Skirting": "经典 201 不锈钢踢脚线",
    "New-Series 201 Stainless Steel Skirting": "新款 201 不锈钢踢脚线",
    "WPC Skirting — 55 mm & 100 mm Series": "WPC 踢脚线 — 55 mm 与 100 mm 系列",
    "L-Shaped Aluminium Edge Trim": "L 型铝合金收边条",
    "F / C-Shaped Aluminium Trim": "F / C 型铝合金收边条",
    "T / U-Shaped Aluminium Transition Trim": "T / U 型铝合金过渡条",
  },
  de: {
    "Crystal-Face Aluminium Skirting": "Aluminium-Sockelleiste mit Kristallfront",
    "Morandi Finish Aluminium Skirting": "Aluminium-Sockelleiste mit Morandi-Oberfläche",
    "Woodgrain Upturned Aluminium Skirting": "Aluminium-Sockelleiste in Holzoptik mit Aufkantung",
    "Dual-Seal Aluminium Skirting": "Aluminium-Sockelleiste mit Doppeldichtung",
    "Flat-Face Aluminium Skirting": "Flache Aluminium-Sockelleiste",
    "Flat-Face Clip-On Aluminium Skirting": "Flache Clip-On Aluminium-Sockelleiste",
    "Soft-Radius Aluminium Skirting": "Aluminium-Sockelleiste mit weichem Radius",
    "Minimal Woodgrain Aluminium Skirting": "Minimalistische Aluminium-Sockelleiste in Holzoptik",
    "Aluminium-Titanium Alloy Skirting": "Aluminium-Titan-Legierungs-Sockelleiste",
    "Seamless Recessed Aluminium Skirting": "Nahtlose eingelassene Aluminium-Sockelleiste",
    "Standard Recessed Aluminium Skirting": "Standard-Einbau-Sockelleiste aus Aluminium",
    "Flush-Mount Recessed Aluminium Skirting": "Flächenbündige Einbau-Sockelleiste aus Aluminium",
    "Plaster-In Aluminium Skirting": "Einputz-Sockelleiste aus Aluminium",
    "Recessed LED Aluminium Skirting": "Eingelassene LED-Aluminium-Sockelleiste",
    "TG Clip-On Solid Wood Skirting": "TG Clip-On Massivholz-Sockelleiste",
    "TG Clip-On Solid Wood Skirting System": "TG Clip-On Massivholz-Sockelleistensystem",
    "Three-Side Painted Solid Wood Skirting": "Dreiseitig lackierte Massivholz-Sockelleiste",
    "Xuanwu & Qilin Solid Wood Series": "Massivholzserie Xuanwu & Qilin",
    "Classic 201 Stainless Steel Skirting": "Klassische 201 Edelstahl-Sockelleiste",
    "New-Series 201 Stainless Steel Skirting": "Neue 201 Edelstahl-Sockelleiste",
    "WPC Skirting — 55 mm & 100 mm Series": "WPC-Sockelleiste — Serie 55 mm & 100 mm",
    "L-Shaped Aluminium Edge Trim": "L-förmiges Aluminium-Kantenprofil",
    "F / C-Shaped Aluminium Trim": "F-/C-förmiges Aluminiumprofil",
    "T / U-Shaped Aluminium Transition Trim": "T-/U-förmiges Aluminium-Übergangsprofil",
  },
  es: {
    "Crystal-Face Aluminium Skirting": "Rodapié de aluminio con cara cristal",
    "Morandi Finish Aluminium Skirting": "Rodapié de aluminio con acabado Morandi",
    "Woodgrain Upturned Aluminium Skirting": "Rodapié de aluminio efecto madera con borde elevado",
    "Dual-Seal Aluminium Skirting": "Rodapié de aluminio con doble sellado",
    "Flat-Face Aluminium Skirting": "Rodapié de aluminio de cara plana",
    "Flat-Face Clip-On Aluminium Skirting": "Rodapié de aluminio clip-on de cara plana",
    "Soft-Radius Aluminium Skirting": "Rodapié de aluminio con radio suave",
    "Minimal Woodgrain Aluminium Skirting": "Rodapié de aluminio minimalista efecto madera",
    "Aluminium-Titanium Alloy Skirting": "Rodapié de aleación aluminio-titanio",
    "Seamless Recessed Aluminium Skirting": "Rodapié de aluminio empotrado sin juntas",
    "Standard Recessed Aluminium Skirting": "Rodapié de aluminio empotrado estándar",
    "Flush-Mount Recessed Aluminium Skirting": "Rodapié de aluminio empotrado enrasado",
    "Plaster-In Aluminium Skirting": "Rodapié de aluminio para enlucir",
    "Recessed LED Aluminium Skirting": "Rodapié de aluminio empotrado con LED",
    "TG Clip-On Solid Wood Skirting": "Rodapié de madera maciza TG clip-on",
    "TG Clip-On Solid Wood Skirting System": "Sistema de rodapié de madera maciza TG clip-on",
    "Three-Side Painted Solid Wood Skirting": "Rodapié de madera maciza pintado en tres caras",
    "Xuanwu & Qilin Solid Wood Series": "Serie de madera maciza Xuanwu y Qilin",
    "Classic 201 Stainless Steel Skirting": "Rodapié clásico de acero inoxidable 201",
    "New-Series 201 Stainless Steel Skirting": "Rodapié nuevo de acero inoxidable 201",
    "WPC Skirting — 55 mm & 100 mm Series": "Rodapié WPC — series de 55 mm y 100 mm",
    "L-Shaped Aluminium Edge Trim": "Remate de borde de aluminio en L",
    "F / C-Shaped Aluminium Trim": "Remate de aluminio en F / C",
    "T / U-Shaped Aluminium Transition Trim": "Perfil de transición de aluminio en T / U",
  },
  fr: {
    "Crystal-Face Aluminium Skirting": "Plinthe aluminium à face cristal",
    "Morandi Finish Aluminium Skirting": "Plinthe aluminium finition Morandi",
    "Woodgrain Upturned Aluminium Skirting": "Plinthe aluminium effet bois à bord relevé",
    "Dual-Seal Aluminium Skirting": "Plinthe aluminium à double joint",
    "Flat-Face Aluminium Skirting": "Plinthe aluminium à face plane",
    "Flat-Face Clip-On Aluminium Skirting": "Plinthe aluminium clip-on à face plane",
    "Soft-Radius Aluminium Skirting": "Plinthe aluminium à rayon adouci",
    "Minimal Woodgrain Aluminium Skirting": "Plinthe aluminium minimaliste effet bois",
    "Aluminium-Titanium Alloy Skirting": "Plinthe en alliage aluminium-titane",
    "Seamless Recessed Aluminium Skirting": "Plinthe aluminium encastrée sans joint",
    "Standard Recessed Aluminium Skirting": "Plinthe aluminium encastrée standard",
    "Flush-Mount Recessed Aluminium Skirting": "Plinthe aluminium encastrée affleurante",
    "Plaster-In Aluminium Skirting": "Plinthe aluminium à noyer dans l’enduit",
    "Recessed LED Aluminium Skirting": "Plinthe aluminium encastrée avec LED",
    "TG Clip-On Solid Wood Skirting": "Plinthe bois massif TG clip-on",
    "TG Clip-On Solid Wood Skirting System": "Système de plinthe bois massif TG clip-on",
    "Three-Side Painted Solid Wood Skirting": "Plinthe bois massif peinte sur trois faces",
    "Xuanwu & Qilin Solid Wood Series": "Série bois massif Xuanwu & Qilin",
    "Classic 201 Stainless Steel Skirting": "Plinthe classique en acier inoxydable 201",
    "New-Series 201 Stainless Steel Skirting": "Nouvelle plinthe en acier inoxydable 201",
    "WPC Skirting — 55 mm & 100 mm Series": "Plinthe WPC — séries 55 mm et 100 mm",
    "L-Shaped Aluminium Edge Trim": "Profil de finition aluminium en L",
    "F / C-Shaped Aluminium Trim": "Profil aluminium en F / C",
    "T / U-Shaped Aluminium Transition Trim": "Profil de transition aluminium en T / U",
  },
};

const commonCopy: Record<LocaleCopy, Record<string, string>> = {
  zh: {
    Home: "首页",
    Products: "产品",
    Applications: "应用场景",
    Downloads: "技术资料",
    "Technical Downloads": "技术资料",
    "Request a Quote": "获取报价",
    "Product Catalogue": "产品目录",
    "Architectural Skirting & Profile Systems": "建筑踢脚线与型材系统",
    "Product Catalogue Architectural Skirting & Profile Systems": "产品目录 建筑踢脚线与型材系统",
    "Our complete range of aluminium, solid wood, stainless steel and composite profiles — manufactured for professional specification. Request technical drawings, order samples or submit an RFQ for any system in this catalogue.": "完整覆盖铝合金、实木、不锈钢和复合型材系统，面向专业项目规格生产。您可以为目录中的任一系统索取技术图纸、订购样品或提交询价。",
    "Filter by:": "筛选：",
    Material: "材质",
    Installation: "安装方式",
    Application: "应用场景",
    Category: "类别",
    "Document type": "文档类型",
    Clear: "清除",
    "Clear filters": "清除筛选",
    "Clear All Filters": "清除所有筛选",
    "All Products": "全部产品",
    All: "全部",
    "材质: All": "材质: 全部",
    "安装方式: All": "安装方式: 全部",
    "应用场景: All": "应用场景: 全部",
    "类别: All": "类别: 全部",
    "文档类型: All": "文档类型: 全部",
    Showing: "显示",
    of: "共",
    systems: "个系统",
    resources: "项资源",
    Aluminium: "铝合金",
    "Stainless Steel": "不锈钢",
    "Solid Wood": "实木",
    Recessed: "嵌入式",
    LED: "LED",
    WPC: "WPC",
    Trims: "收边条",
    "Surface-Mounted": "明装",
    "Clip-on": "卡扣式",
    Residential: "住宅",
    Hospitality: "酒店与公寓",
    Workplace: "办公空间",
    Healthcare: "医疗与厨房",
    Commercial: "商业",
    "View Product": "查看产品",
    "View Products": "查看产品",
    "View all products": "查看全部产品",
    "Browse Products": "浏览产品",
    "Technical Resources": "技术资料",
    "Request Pack": "索取资料包",
    Request: "索取",
    "Resource": "资源",
    Formats: "格式",
    Status: "状态",
    "Available on request": "可按需提供",
    "In preparation": "准备中",
    "Project-specific": "按项目提供",
    "All Categories": "全部类别",
    "All Types": "全部类型",
    "Profile Drawing": "型材图纸",
    "Installation Instructions": "安装说明",
    "Test Report": "测试报告",
    "Packaging Specifications": "包装规格",
    "Aluminium Skirting": "铝合金踢脚线",
    "Recessed Systems": "嵌入式系统",
    "LED Systems": "LED 系统",
    "LED Skirting Systems": "LED 踢脚线系统",
    "WPC Skirting": "WPC 踢脚线",
    "Stainless Steel Skirting": "不锈钢踢脚线",
    "Trims & Profiles": "收边条与型材",
    "Technical documents": "技术文档",
    Specifications: "规格",
    "Confirmed per project": "按项目确认",
    "Specification approach": "规格确认方式",
    "Related products": "相关产品",
    "Explore the same product family.": "浏览同一产品系列。",
    "Additional related products are available on request.": "更多相关产品可按需提供。",
    "Request catalogue packs, drawings and test data.": "索取目录资料包、图纸和测试数据。",
    "Request catalogue packs,": "索取目录资料包、",
    "drawings and test data.": "图纸和测试数据。",
    "Our final public download library is still being prepared. During pre-launch, BINGE shares tailored document packs after you confirm the product family, target market and project use. This keeps catalogue pages, drawings, test reports and packaging specs accurate.": "最终公开下载库仍在准备中。预上线期间，BINGE 会在确认产品系列、目标市场和项目用途后提供定制文档包，确保目录页、图纸、测试报告和包装规格准确。",
    "Pre-launch document request mode": "预上线资料申请模式",
    "No placeholder PDF links are shown here. Buyers can request the right technical pack through the RFQ form.": "这里不展示占位 PDF 链接。买家可通过询价表索取匹配的技术资料包。",
    "Search by title, product code or document note…": "按标题、产品代码或文档说明搜索…",
    "No resources match your search.": "没有匹配的资源。",
    "Try a different search term or clear your filters to see all available resource types.": "请尝试其他关键词，或清除筛选查看所有资源类型。",
    "Technical Support": "技术支持",
    "Need a specific drawing or specification?": "需要特定图纸或规格？",
    "Need a specific drawingor specification?": "需要特定图纸或规格？",
    "Request a Document Pack": "索取文档资料包",
    "Contact Information": "联系信息",
    "Contact Details": "联系方式",
    "Product Requirements": "产品需求",
    Logistics: "物流信息",
    "Full Name": "姓名",
    "Company Name": "公司名称",
    Country: "国家/地区",
    "Business Type": "业务类型",
    "Email Address": "邮箱地址",
    "WhatsApp or Phone": "WhatsApp 或电话",
    "Product Category": "产品类别",
    "Product Code": "产品代码",
    "Product Code (if known)": "产品代码（如已知）",
    "产品代码 (if known)": "产品代码（如已知）",
    "Estimated Quantity": "预计数量",
    "Required Finish": "所需表面处理",
    "所需表面处理 (if known)": "所需表面处理（如已知）",
    "(if known)": "（如已知）",
    "Target Delivery Date": "目标交付日期",
    "目标交付日期 (optional)": "目标交付日期（可选）",
    "Destination Port": "目的港",
    "Technical Drawing or Reference File": "技术图纸或参考文件",
    "技术图纸或参考文件 (optional)": "技术图纸或参考文件（可选）",
    "(optional)": "（可选）",
    "Project Details": "项目详情",
    "Submit RFQ": "提交询价",
    "Submitting...": "正在提交…",
    "RFQ": "询价",
    "Tell us what your project needs.": "告诉我们您的项目需求。",
    "Tell us what your": "告诉我们您的",
    "project needs.": "项目需求。",
    "Send your product, quantity, finish and logistics requirements to the BINGE team so they can prepare the right quotation path for your project.": "请将产品、数量、表面处理和物流需求发送给 BINGE 团队，我们会为您的项目准备合适的报价路径。",
    "Fields marked * are required.": "带 * 的字段为必填项。",
    "Fields marked": "带",
    "are required.": "为必填项。",
    "Secure RFQ submission:": "安全询价提交：",
    "required details are sent to BINGE for follow-up. Only non-sensitive project selections are saved as a browser draft before submission; contact details, messages, consent and files are never persisted locally.": "必填信息会发送给 BINGE 用于后续跟进。提交前仅非敏感项目选择会作为浏览器草稿保存；联系方式、留言、授权和文件不会保存在本地。",
    "Click to upload or drag and drop": "点击上传或拖放文件",
    "Select country…": "选择国家/地区…",
    "Select business type…": "选择业务类型…",
    Australia: "澳大利亚",
    Austria: "奥地利",
    Belgium: "比利时",
    Canada: "加拿大",
    China: "中国",
    "Czech Republic": "捷克共和国",
    Denmark: "丹麦",
    Finland: "芬兰",
    France: "法国",
    Germany: "德国",
    Greece: "希腊",
    Hungary: "匈牙利",
    Ireland: "爱尔兰",
    Italy: "意大利",
    Japan: "日本",
    Netherlands: "荷兰",
    "New Zealand": "新西兰",
    Norway: "挪威",
    Poland: "波兰",
    Portugal: "葡萄牙",
    Romania: "罗马尼亚",
    Singapore: "新加坡",
    "South Africa": "南非",
    Spain: "西班牙",
    Sweden: "瑞典",
    Switzerland: "瑞士",
    Turkey: "土耳其",
    "United Kingdom": "英国",
    "United States": "美国",
    Other: "其他",
    "Building Material Importer": "建材进口商",
    "Flooring Distributor": "地材经销商",
    "Architect or Interior Designer": "建筑师或室内设计师",
    "Interior Fit-Out Contractor": "室内精装承包商",
    "Wholesaler or Stockist": "批发商或库存商",
    "Property Developer": "地产开发商",
    "Procurement Manager": "采购经理",
    "End User / Other": "终端用户 / 其他",
    "Include country code. We may use WhatsApp for quick clarifications.": "请包含国家区号。我们可能会通过 WhatsApp 快速确认细节。",
    "Select category…": "选择类别…",
    "Recessed & Shadow Gap Systems": "嵌入式与阴影缝系统",
    "Solid Wood Skirting": "实木踢脚线",
    "Trims & Finishing Profiles": "收边条与收口型材",
    Accessories: "配件",
    "Multiple / Not yet decided": "多个类别 / 尚未决定",
    "if known": "如已知",
    "Not yet decided": "尚未决定",
    "Brushed Anodised": "拉丝阳极氧化",
    "Mill Finish Anodised": "本色阳极氧化",
    "Custom Anodised Colour": "定制阳极氧化颜色",
    "Powder Coat (RAL)": "粉末喷涂（RAL）",
    "Custom Powder Coat Colour": "定制粉末喷涂颜色",
    "Mirror Polish": "镜面抛光",
    "PDF, DXF, DWG, STEP, JPG or PNG — max 10 MB": "PDF、DXF、DWG、STEP、JPG 或 PNG — 最大 10 MB",
    "A profile drawing or site reference helps us prepare a more accurate quotation.": "型材图纸或现场参考资料有助于我们准备更准确的报价。",
    "I agree to BINGE's privacy notice and agree that BINGE may use these details to respond to my RFQ.": "我同意 BINGE 的隐私声明，并同意 BINGE 使用这些信息回复我的询价。",
    "I agree to BINGE's": "我同意 BINGE 的",
    "privacy notice and agree that BINGE may use these details to respond to my RFQ.": "隐私声明，并同意 BINGE 使用这些信息回复我的询价。",
    "Your enquiry is sent to BINGE for quotation follow-up.": "您的询价将发送给 BINGE，用于后续报价跟进。",
    "Submit Another Request": "提交新的询价",
    "RFQ Submitted": "询价已提交",
    "Request received.": "请求已收到。",
    "What happens next": "后续流程",
  },
  de: {
    Home: "Startseite",
    Products: "Produkte",
    Applications: "Anwendungen",
    Downloads: "Downloads",
    "Technical Downloads": "Technische Downloads",
    "Request a Quote": "Angebot anfordern",
    "Product Catalogue": "Produktkatalog",
    "Architectural Skirting & Profile Systems": "Architektonische Sockelleisten- und Profilsysteme",
    "Our complete range of aluminium, solid wood, stainless steel and composite profiles — manufactured for professional specification. Request technical drawings, order samples or submit an RFQ for any system in this catalogue.": "Unser komplettes Sortiment aus Aluminium-, Massivholz-, Edelstahl- und Verbundprofilen wird für professionelle Spezifikationen gefertigt. Fordern Sie technische Zeichnungen, Muster oder ein RFQ für jedes System in diesem Katalog an.",
    "Filter by:": "Filtern nach:",
    Material: "Material",
    Installation: "Montage",
    Application: "Anwendung",
    Category: "Kategorie",
    "Document type": "Dokumenttyp",
    Clear: "Zurücksetzen",
    "Clear filters": "Filter löschen",
    "Clear All Filters": "Alle Filter löschen",
    "All Products": "Alle Produkte",
    All: "Alle",
    Showing: "Anzeige",
    of: "von",
    systems: "Systeme",
    resources: "Ressourcen",
    Aluminium: "Aluminium",
    "Stainless Steel": "Edelstahl",
    "Solid Wood": "Massivholz",
    Recessed: "Eingelassen",
    LED: "LED",
    WPC: "WPC",
    Trims: "Profile",
    "Surface-Mounted": "Aufputz",
    "Clip-on": "Clip-on",
    Residential: "Wohnen",
    Hospitality: "Hospitality",
    Workplace: "Arbeitswelten",
    Healthcare: "Gesundheit",
    Commercial: "Gewerbe",
    "View Product": "Produkt ansehen",
    "View Products": "Produkte ansehen",
    "View all products": "Alle Produkte ansehen",
    "Browse Products": "Produkte durchsuchen",
    "Technical Resources": "Technische Unterlagen",
    "Request Pack": "Paket anfordern",
    Request: "Anfragen",
    Resource: "Ressource",
    Formats: "Formate",
    Status: "Status",
    "Available on request": "Auf Anfrage verfügbar",
    "In preparation": "In Vorbereitung",
    "Project-specific": "Projektspezifisch",
    "All Categories": "Alle Kategorien",
    "All Types": "Alle Typen",
    "Profile Drawing": "Profilzeichnung",
    "Installation Instructions": "Montageanleitung",
    "Test Report": "Prüfbericht",
    "Packaging Specifications": "Verpackungsspezifikation",
    "Aluminium Skirting": "Aluminium-Sockelleisten",
    "Recessed Systems": "Einbausysteme",
    "LED Systems": "LED-Systeme",
    "WPC Skirting": "WPC-Sockelleisten",
    "Trims & Profiles": "Abschluss- und Profilsysteme",
    "Technical documents": "Technische Dokumente",
    Specifications: "Spezifikationen",
    "Confirmed per project": "Je Projekt bestätigt",
    "Specification approach": "Spezifikationsprozess",
    "Related products": "Ähnliche Produkte",
    "Explore the same product family.": "Entdecken Sie dieselbe Produktfamilie.",
    "Additional related products are available on request.": "Weitere ähnliche Produkte sind auf Anfrage verfügbar.",
    "Request catalogue packs, drawings and test data.": "Katalogpakete, Zeichnungen und Prüfdaten anfordern.",
    "Request catalogue packs,": "Katalogpakete,",
    "drawings and test data.": "Zeichnungen und Prüfdaten anfordern.",
    "Our final public download library is still being prepared. During pre-launch, BINGE shares tailored document packs after you confirm the product family, target market and project use. This keeps catalogue pages, drawings, test reports and packaging specs accurate.": "Die finale öffentliche Download-Bibliothek wird noch vorbereitet. Vor dem Launch stellt BINGE nach Bestätigung von Produktfamilie, Zielmarkt und Projekteinsatz passende Dokumentenpakete bereit.",
    "Pre-launch document request mode": "Dokumentenanforderung vor dem Launch",
    "No resources match your search.": "Keine passenden Ressourcen gefunden.",
    "Technical Support": "Technischer Support",
    "Need a specific drawing or specification?": "Benötigen Sie eine bestimmte Zeichnung oder Spezifikation?",
    "Need a specific drawingor specification?": "Benötigen Sie eine bestimmte Zeichnung oder Spezifikation?",
    "Request a Document Pack": "Dokumentenpaket anfordern",
    "Contact Information": "Kontaktinformationen",
    "Contact Details": "Kontaktdaten",
    "Product Requirements": "Produktanforderungen",
    Logistics: "Logistik",
    "Full Name": "Vollständiger Name",
    "Company Name": "Firmenname",
    Country: "Land",
    "Business Type": "Geschäftstyp",
    "Email Address": "E-Mail-Adresse",
    "WhatsApp or Phone": "WhatsApp oder Telefon",
    "Product Category": "Produktkategorie",
    "Product Code": "Produktcode",
    "Estimated Quantity": "Geschätzte Menge",
    "Required Finish": "Gewünschte Oberfläche",
    "Target Delivery Date": "Gewünschter Liefertermin",
    "Destination Port": "Zielhafen",
    "Technical Drawing or Reference File": "Technische Zeichnung oder Referenzdatei",
    "Project Details": "Projektdetails",
    "Submit RFQ": "RFQ senden",
    "Submitting...": "Wird gesendet…",
    "Tell us what your project needs.": "Erzählen Sie uns von Ihrem Projekt.",
    "Tell us what your": "Sagen Sie uns, was Ihr",
    "project needs.": "Projekt benötigt.",
    "Send your product, quantity, finish and logistics requirements to the BINGE team so they can prepare the right quotation path for your project.": "Senden Sie Produkt-, Mengen-, Oberflächen- und Logistikanforderungen an das BINGE-Team, damit wir den passenden Angebotsweg vorbereiten können.",
    "Fields marked * are required.": "Mit * markierte Felder sind Pflichtfelder.",
    "Fields marked": "Mit",
    "are required.": "markierte Felder sind Pflichtfelder.",
    "Secure RFQ submission:": "Sichere RFQ-Übermittlung:",
    "required details are sent to BINGE for follow-up. Only non-sensitive project selections are saved as a browser draft before submission; contact details, messages, consent and files are never persisted locally.": "Erforderliche Angaben werden zur Nachverfolgung an BINGE gesendet. Vor dem Absenden werden nur nicht sensible Projektauswahlen als Browser-Entwurf gespeichert.",
    "Select country…": "Land auswählen…",
    "Select business type…": "Geschäftstyp auswählen…",
  },
  es: {
    Home: "Inicio",
    Products: "Productos",
    Applications: "Aplicaciones",
    Downloads: "Descargas",
    "Technical Downloads": "Descargas técnicas",
    "Request a Quote": "Solicitar presupuesto",
    "Product Catalogue": "Catálogo de productos",
    "Architectural Skirting & Profile Systems": "Sistemas arquitectónicos de rodapiés y perfiles",
    "Our complete range of aluminium, solid wood, stainless steel and composite profiles — manufactured for professional specification. Request technical drawings, order samples or submit an RFQ for any system in this catalogue.": "Nuestra gama completa de perfiles de aluminio, madera maciza, acero inoxidable y materiales compuestos está fabricada para especificaciones profesionales. Solicite planos técnicos, muestras o una RFQ para cualquier sistema del catálogo.",
    "Filter by:": "Filtrar por:",
    Material: "Material",
    Installation: "Instalación",
    Application: "Aplicación",
    Category: "Categoría",
    "Document type": "Tipo de documento",
    Clear: "Limpiar",
    "Clear filters": "Limpiar filtros",
    "Clear All Filters": "Limpiar todos los filtros",
    "All Products": "Todos los productos",
    All: "Todo",
    Showing: "Mostrando",
    of: "de",
    systems: "sistemas",
    resources: "recursos",
    Aluminium: "Aluminio",
    "Stainless Steel": "Acero inoxidable",
    "Solid Wood": "Madera maciza",
    Recessed: "Empotrado",
    LED: "LED",
    WPC: "WPC",
    Trims: "Remates",
    "Surface-Mounted": "Montaje en superficie",
    "Clip-on": "Clip-on",
    Residential: "Residencial",
    Hospitality: "Hostelería",
    Workplace: "Oficinas",
    Healthcare: "Sanitario",
    Commercial: "Comercial",
    "View Product": "Ver producto",
    "View Products": "Ver productos",
    "View all products": "Ver todos los productos",
    "Browse Products": "Explorar productos",
    "Technical Resources": "Recursos técnicos",
    "Request Pack": "Solicitar pack",
    Request: "Solicitar",
    Resource: "Recurso",
    Formats: "Formatos",
    Status: "Estado",
    "Available on request": "Disponible bajo solicitud",
    "In preparation": "En preparación",
    "Project-specific": "Específico del proyecto",
    "All Categories": "Todas las categorías",
    "All Types": "Todos los tipos",
    "Profile Drawing": "Plano de perfil",
    "Installation Instructions": "Instrucciones de instalación",
    "Test Report": "Informe de ensayo",
    "Packaging Specifications": "Especificaciones de embalaje",
    "Aluminium Skirting": "Rodapiés de aluminio",
    "Recessed Systems": "Sistemas empotrados",
    "LED Systems": "Sistemas LED",
    "WPC Skirting": "Rodapiés WPC",
    "Trims & Profiles": "Remates y perfiles",
    "Technical documents": "Documentos técnicos",
    Specifications: "Especificaciones",
    "Confirmed per project": "Confirmado por proyecto",
    "Specification approach": "Enfoque de especificación",
    "Related products": "Productos relacionados",
    "Explore the same product family.": "Explore la misma familia de productos.",
    "Additional related products are available on request.": "Hay productos relacionados adicionales bajo solicitud.",
    "Request catalogue packs, drawings and test data.": "Solicite catálogos, planos y datos de ensayo.",
    "Request catalogue packs,": "Solicite catálogos,",
    "drawings and test data.": "planos y datos de ensayo.",
    "Our final public download library is still being prepared. During pre-launch, BINGE shares tailored document packs after you confirm the product family, target market and project use. This keeps catalogue pages, drawings, test reports and packaging specs accurate.": "La biblioteca pública final de descargas aún está en preparación. Antes del lanzamiento, BINGE comparte packs documentales adaptados tras confirmar la familia de producto, el mercado objetivo y el uso del proyecto.",
    "Pre-launch document request mode": "Modo de solicitud de documentos previo al lanzamiento",
    "No resources match your search.": "No hay recursos que coincidan con su búsqueda.",
    "Technical Support": "Soporte técnico",
    "Need a specific drawing or specification?": "¿Necesita un plano o una especificación concreta?",
    "Need a specific drawingor specification?": "¿Necesita un plano o una especificación concreta?",
    "Request a Document Pack": "Solicitar pack documental",
    "Contact Information": "Información de contacto",
    "Contact Details": "Datos de contacto",
    "Product Requirements": "Requisitos del producto",
    Logistics: "Logística",
    "Full Name": "Nombre completo",
    "Company Name": "Nombre de la empresa",
    Country: "País",
    "Business Type": "Tipo de negocio",
    "Email Address": "Correo electrónico",
    "WhatsApp or Phone": "WhatsApp o teléfono",
    "Product Category": "Categoría de producto",
    "Product Code": "Código de producto",
    "Estimated Quantity": "Cantidad estimada",
    "Required Finish": "Acabado requerido",
    "Target Delivery Date": "Fecha objetivo de entrega",
    "Destination Port": "Puerto de destino",
    "Technical Drawing or Reference File": "Plano técnico o archivo de referencia",
    "Project Details": "Detalles del proyecto",
    "Submit RFQ": "Enviar RFQ",
    "Submitting...": "Enviando…",
    "Tell us what your project needs.": "Cuéntenos qué necesita su proyecto.",
    "Tell us what your": "Cuéntenos qué necesita",
    "project needs.": "su proyecto.",
    "Send your product, quantity, finish and logistics requirements to the BINGE team so they can prepare the right quotation path for your project.": "Envíe al equipo de BINGE los requisitos de producto, cantidad, acabado y logística para preparar la ruta de presupuesto adecuada.",
    "Fields marked * are required.": "Los campos marcados con * son obligatorios.",
    "Fields marked": "Los campos marcados",
    "are required.": "son obligatorios.",
    "Secure RFQ submission:": "Envío seguro de RFQ:",
    "required details are sent to BINGE for follow-up. Only non-sensitive project selections are saved as a browser draft before submission; contact details, messages, consent and files are never persisted locally.": "Los datos obligatorios se envían a BINGE para seguimiento. Antes del envío solo se guardan como borrador del navegador selecciones no sensibles del proyecto.",
    "Select country…": "Seleccione país…",
    "Select business type…": "Seleccione tipo de negocio…",
  },
  fr: {
    Home: "Accueil",
    Products: "Produits",
    Applications: "Applications",
    Downloads: "Téléchargements",
    "Technical Downloads": "Téléchargements techniques",
    "Request a Quote": "Demander un devis",
    "Product Catalogue": "Catalogue produits",
    "Architectural Skirting & Profile Systems": "Systèmes architecturaux de plinthes et profilés",
    "Our complete range of aluminium, solid wood, stainless steel and composite profiles — manufactured for professional specification. Request technical drawings, order samples or submit an RFQ for any system in this catalogue.": "Notre gamme complète de profilés en aluminium, bois massif, acier inoxydable et composite est fabriquée pour les spécifications professionnelles. Demandez plans techniques, échantillons ou RFQ pour tout système du catalogue.",
    "Filter by:": "Filtrer par :",
    Material: "Matériau",
    Installation: "Pose",
    Application: "Application",
    Category: "Catégorie",
    "Document type": "Type de document",
    Clear: "Effacer",
    "Clear filters": "Effacer les filtres",
    "Clear All Filters": "Effacer tous les filtres",
    "All Products": "Tous les produits",
    All: "Tous",
    Showing: "Affichage",
    of: "sur",
    systems: "systèmes",
    resources: "ressources",
    Aluminium: "Aluminium",
    "Stainless Steel": "Acier inoxydable",
    "Solid Wood": "Bois massif",
    Recessed: "Encastré",
    LED: "LED",
    WPC: "WPC",
    Trims: "Finitions",
    "Surface-Mounted": "En applique",
    "Clip-on": "Clip-on",
    Residential: "Résidentiel",
    Hospitality: "Hôtellerie",
    Workplace: "Bureaux",
    Healthcare: "Santé",
    Commercial: "Commercial",
    "View Product": "Voir le produit",
    "View Products": "Voir les produits",
    "View all products": "Voir tous les produits",
    "Browse Products": "Parcourir les produits",
    "Technical Resources": "Ressources techniques",
    "Request Pack": "Demander le pack",
    Request: "Demander",
    Resource: "Ressource",
    Formats: "Formats",
    Status: "Statut",
    "Available on request": "Disponible sur demande",
    "In preparation": "En préparation",
    "Project-specific": "Spécifique au projet",
    "All Categories": "Toutes les catégories",
    "All Types": "Tous les types",
    "Profile Drawing": "Plan de profil",
    "Installation Instructions": "Instructions de pose",
    "Test Report": "Rapport d’essai",
    "Packaging Specifications": "Spécifications d’emballage",
    "Aluminium Skirting": "Plinthes aluminium",
    "Recessed Systems": "Systèmes encastrés",
    "LED Systems": "Systèmes LED",
    "WPC Skirting": "Plinthes WPC",
    "Trims & Profiles": "Finitions et profilés",
    "Technical documents": "Documents techniques",
    Specifications: "Spécifications",
    "Confirmed per project": "Confirmé par projet",
    "Specification approach": "Approche de spécification",
    "Related products": "Produits associés",
    "Explore the same product family.": "Explorer la même famille de produits.",
    "Additional related products are available on request.": "D’autres produits associés sont disponibles sur demande.",
    "Request catalogue packs, drawings and test data.": "Demander catalogues, plans et données d’essai.",
    "Request catalogue packs,": "Demander catalogues,",
    "drawings and test data.": "plans et données d’essai.",
    "Our final public download library is still being prepared. During pre-launch, BINGE shares tailored document packs after you confirm the product family, target market and project use. This keeps catalogue pages, drawings, test reports and packaging specs accurate.": "La bibliothèque publique finale de téléchargements est encore en préparation. Avant le lancement, BINGE fournit des packs documentaires adaptés après confirmation de la famille produit, du marché cible et de l’usage projet.",
    "Pre-launch document request mode": "Mode de demande documentaire avant lancement",
    "No resources match your search.": "Aucune ressource ne correspond à votre recherche.",
    "Technical Support": "Support technique",
    "Need a specific drawing or specification?": "Besoin d’un plan ou d’une spécification précise ?",
    "Need a specific drawingor specification?": "Besoin d’un plan ou d’une spécification précise ?",
    "Request a Document Pack": "Demander un pack documentaire",
    "Contact Information": "Informations de contact",
    "Contact Details": "Coordonnées",
    "Product Requirements": "Exigences produit",
    Logistics: "Logistique",
    "Full Name": "Nom complet",
    "Company Name": "Nom de l’entreprise",
    Country: "Pays",
    "Business Type": "Type d’activité",
    "Email Address": "Adresse e-mail",
    "WhatsApp or Phone": "WhatsApp ou téléphone",
    "Product Category": "Catégorie de produit",
    "Product Code": "Code produit",
    "Estimated Quantity": "Quantité estimée",
    "Required Finish": "Finition souhaitée",
    "Target Delivery Date": "Date de livraison souhaitée",
    "Destination Port": "Port de destination",
    "Technical Drawing or Reference File": "Plan technique ou fichier de référence",
    "Project Details": "Détails du projet",
    "Submit RFQ": "Envoyer la RFQ",
    "Submitting...": "Envoi…",
    "Tell us what your project needs.": "Parlez-nous des besoins de votre projet.",
    "Tell us what your": "Dites-nous ce dont",
    "project needs.": "votre projet a besoin.",
    "Send your product, quantity, finish and logistics requirements to the BINGE team so they can prepare the right quotation path for your project.": "Envoyez vos exigences de produit, quantité, finition et logistique à l’équipe BINGE afin de préparer le bon parcours de devis.",
    "Fields marked * are required.": "Les champs marqués * sont obligatoires.",
    "Fields marked": "Les champs marqués",
    "are required.": "sont obligatoires.",
    "Secure RFQ submission:": "Soumission RFQ sécurisée :",
    "required details are sent to BINGE for follow-up. Only non-sensitive project selections are saved as a browser draft before submission; contact details, messages, consent and files are never persisted locally.": "Les informations obligatoires sont envoyées à BINGE pour suivi. Avant l’envoi, seules les sélections projet non sensibles sont enregistrées comme brouillon dans le navigateur.",
    "Select country…": "Sélectionner le pays…",
    "Select business type…": "Sélectionner le type d’activité…",
  },
};

const phraseCopy: Record<LocaleCopy, Record<string, string>> = {
  zh: {
    "Decorative aluminium skirting family with a polished face treatment and clip-on installation.": "带抛光装饰面的铝合金踢脚线系列，采用卡扣式安装。",
    "Muted colour aluminium range developed for contemporary residential and interior fit-out projects.": "为现代住宅和室内精装项目开发的柔和色系铝合金产品。",
    "Wood-effect aluminium face with a raised upper edge for a more decorative wall transition.": "木纹铝合金饰面搭配上翻边，让墙地过渡更具装饰性。",
    "Aluminium profile family with upper and lower sealing strips; final dimensions are confirmed per enquiry.": "配备上下密封条的铝合金型材系列，最终尺寸按询价确认。",
    "Straight architectural face available in multiple heights, colours and clip configurations.": "直线型建筑饰面，可按项目选择多种高度、颜色和卡扣配置。",
    "Straight aluminium face with a small-radius edge for a softer transition at the top of the profile.": "直面铝合金型材带小圆弧上边缘，顶部过渡更柔和。",
    "Minimal straight aluminium profile finished with a wood-effect decorative surface.": "极简直线铝合金型材，表面为木纹装饰效果。",
    "Metal skirting family supplied in several profile heights and finish options for project selection.": "金属踢脚线系列，可按项目选择多种高度和表面处理。",
    "Recessed profile designed for a low-visibility transition between the finished wall and floor.": "嵌入式型材，用于在完成面墙体与地面之间形成低可见度过渡。",
    "Recessed aluminium family with separate base and visible face components for interior specification.": "嵌入式铝合金系列，包含独立底座和可见饰面件，适合室内规格选型。",
    "Flush-mounted recessed face for clean junctions in modern wall and panel systems.": "齐平嵌入式饰面，适用于现代墙面与板材系统的利落收口。",
    "Perforated plaster-in base profile with a visible lower face; sizes and finishes are confirmed on request.": "带孔抹灰底座型材和可见下饰面，尺寸与表面处理按需确认。",
    "Recessed aluminium profile with an integrated channel for floor-level linear lighting.": "带集成灯槽的嵌入式铝合金型材，用于地脚线性照明。",
    "BINGE TG system with a separate base and solid-wood face board for concealed installation.": "BINGE TG 系统采用独立底座和实木饰面板，实现隐藏式安装。",
    "Solid-wood skirting range with painted faces and several profile heights for interior projects.": "实木踢脚线系列，带喷漆饰面并提供多种高度，适合室内项目。",
    "Decorative solid-wood profile family supplied in multiple heights and face geometries.": "装饰性实木型材系列，可提供多种高度与饰面造型。",
    "Classic stainless-steel skirting family available in several heights and surface colours.": "经典不锈钢踢脚线系列，提供多种高度和表面颜色。",
    "Updated stainless-steel face profile with coordinated accessories and finish options.": "升级版不锈钢饰面型材，配套附件和表面处理选项齐全。",
    "Clip-on WPC skirting family offered in two principal height groups and multiple decorative surfaces.": "卡扣式 WPC 踢脚线系列，提供两组主要高度和多种装饰表面。",
    "L-shaped aluminium trim family for exposed edges, panel junctions and finishing details.": "L 型铝合金收边条系列，适用于外露边、板材接缝和收口细节。",
    "F- and C-shaped aluminium finishing profiles for tile and panel edge conditions.": "F 型和 C 型铝合金收口型材，适用于瓷砖和板材边缘。",
    "T- and U-shaped transition profiles for joining and finishing adjacent surface materials.": "T 型和 U 型过渡型材，用于相邻表面材料的连接和收口。",
  },
  de: {},
  es: {},
  fr: {},
};

export function normalizeCopy(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

export function translateCopy(value: string, locale: Locale) {
  if (locale === "en") return value;
  const key = normalizeCopy(value);
  const copy = { ...commonCopy[locale], ...productCopy[locale], ...phraseCopy[locale] };
  const selectAll = key.match(/^(.+): All$/);
  if (selectAll) {
    const label = copy[selectAll[1]] ?? selectAll[1];
    const all = copy.All ?? "All";
    return `${label}: ${all}`;
  }
  const showingSystems = key.match(/^Showing (\d+) systems$/);
  if (showingSystems) {
    if (locale === "zh") return `显示 ${showingSystems[1]} 个系统`;
    if (locale === "de") return `${showingSystems[1]} Systeme angezeigt`;
    if (locale === "es") return `Mostrando ${showingSystems[1]} sistemas`;
    return `${showingSystems[1]} systèmes affichés`;
  }
  const showingResources = key.match(/^Showing (\d+) of (\d+) resources$/);
  if (showingResources) {
    if (locale === "zh") return `显示 ${showingResources[1]} / ${showingResources[2]} 项资源`;
    if (locale === "de") return `${showingResources[1]} von ${showingResources[2]} Ressourcen angezeigt`;
    if (locale === "es") return `Mostrando ${showingResources[1]} de ${showingResources[2]} recursos`;
    return `${showingResources[1]} ressource(s) sur ${showingResources[2]} affichée(s)`;
  }
  return copy[key] ?? value;
}
